import { useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";


export default function Home() {
  const { data: posts } = api.post.getAll.useQuery();
  // console.log("Posts are: ...", posts);




  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#6d4602] to-[#2c2415]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white"></p>
            <p className="text-center text-2xl text-white">
              {sessionData && (
                <span>Logged in as {sessionData.user?.name}</span>
              )}
            </p>
            {sessionData &&
              posts?.map((post) => (
                <div key={post.id}>
                  <h3>Title: {post.title}</h3>
                  <p>{post.body}</p>
                </div>
              ))}
          </div>
        </div>

      </main>
    </>
  );
}
