import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";
import { toast } from "react-toastify";

export function newPostForm() {
  const session = useSession();
  if (session.status !== "authenticated") return null;

  return <Form />;
}

function Form() {
  const session = useSession();
  const [titleValue, setTitleValue] = useState("");
  const createPost = api.post.createPost.useMutation({
    onSuccess() {
      setTitleValue("");
      if (session.status !== "authenticated") return;
    },
    onError(error) {
      toast(error.message, {
        type: "error",
        position: "top-right",
      });
    },
  });
  return <></>;
}

export default function Home() {
  const { data: posts } = api.post.getAllPosts.useQuery({ limit: 5, page: 1 });
  // console.log("Posts are: ...", posts);

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#6d4602] to-[#2c2415]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white"></p>
            <p className="text-center text-2xl text-white">
              {sessionData && (
                <>
                  <span>Logged in as {sessionData.user?.name}</span>
                  <br />
                  <span>User level is {sessionData.user?.role}</span>
                </>
              )}
            </p>
            {sessionData &&
              posts?.data.posts.map((post, idx) => {
                console.log(post);
                return (
                  <div className="posts" key={idx}>
                    <h1>{post.title}</h1>
                  </div>
                );
              })}
          </div>
        </div>
      </main>
    </>
  );
}
